### PR TITLE
Avoid dependency on env var

### PR DESCRIPTION
**Pull request by shuntagami**
It's better to avoid dependency on env var to make it flexible.

### CODE REVIEW

**Comment by shuntagami** [comment]
@r0busta Is it possible to adopt this change?

**Comment by r0busta** [comment]
@shuntagami, that is a reasonable suggestion, and it's already implemented. If you check the `NewClient` function in `client.go`, it has the required signature and doesn't depend on env vars.

Meanwhile, `NewDefaultClient` is a "convenience" function and can be ignored.

**Comment by r0busta** [comment]
> It's better to avoid dependency on env var to make it flexible.

Does it brake your build or tests?

**Comment by shuntagami** [comment]
@r0busta 
> Does it brake your build or tests?

No.

By the way, I want to call  Shopify GraphQL Admin API using `X-Shopify-Access-Token` and shop name. 

https://github.com/r0busta/go-shopify-graphql/blob/master/graphql/graphql.go#L36-L40
I guess `WithToken` func is for that use case, but I couldn't use the func because it's in `graphqlclient` package (separated from `shopify` package)

May I work on this issue?

**Comment by r0busta** [comment]
@shuntagami, that'd be a great improvement. However, that would require revamping the API in the direction of using more mature patterns (e.g., using contexts or dependency injection).

For now, would something like this work for you:
```go
	const storeName = "mystore"
	const token = "mytoken"
	const version = "2022-04"

	opts := []graphqlclient.Option{
		graphqlclient.WithVersion(version),
		graphqlclient.WithToken(token),
	}

	client := shopify.NewClient("", "", "", shopify.WithGraphQLClient(graphqlclient.NewClient(storeName, opts...)))
	c, err := client.Collection.Get("gid://shopify/Collection/1")
```
Note: `apiKey string, password string, storeName string` args in `shopify.NewClient` not required and can be ignored if the `graphqlclient` is configured properly.

**Pull request closed without merging**
